Bootstrap: docker
From: python:latest

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-porechop
    COPYRIGHT Copyright © 2024 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 0.2.4

%post
    apt update
    apt install -y git
    cd /opt
    git clone https://github.com/rrwick/Porechop.git
    cd Porechop
    python3 setup.py install

%runscript
    porechop "$@"
